# Questions:
1. Build a ​ Python​ process that gets data from the European Central Banks’ currency rates exchange service
1. How did you perform error handling and situations when the service limits the requests per day/hour?
2. How would you make the process to perform better? What would you do differently in
order to run the process faster?


## Solution
1. there is no need to make a request to `https://sdw-wsrest.ecb.europa.eu/` for every call. The solution is to make a big data set of the exchange rates locally and get the user answer from our data set. `The dataset contains all different possible exchange currency rates to EUR.` to get all historicall data, this data set could be complete by time. for example, if the limit is `N` then we make `N-1` requests every day to complete our data set day by day.  the timing could be handled by `Celery` or `FlaskRQ`. for example every day we could make `N-1` API call by this method.

1. making a local data set could make everything faster also.
1. Also using `Numpy & Pandas(python lib)` and `indexing` the `TIME_PERIOD`  column, have a `huge effect` to make things faster.

# IMPORTANT
### this solution is based on address the concerns

## The `X-EUR local dataset` could be built as below:

In [1]:
import io
import numpy as np
import pandas as pd
import requests
from datetime import datetime
from dateutil.relativedelta import relativedelta


def url_maker(from_currency, entrypoint='https://sdw-wsrest.ecb.europa.eu/service/', resource='data', flowRef='EXR', ):
    """ To make the endpoint
    """
    key = 'D.{}.EUR.SP00.A'.format(from_currency)
    return entrypoint + resource + '/' + flowRef + '/' + key


def request_maker(url, from_date, to_date, headers={'Accept': 'text/csv'}):
    """ To get the response of exchange rate from x to EUR
    """
    parameters = {
        'startPeriod': from_date.strftime('%Y-%m-%d'),
        'endPeriod': to_date.strftime('%Y-%m-%d'),
    }
    response = requests.get(url, params=parameters, headers=headers, )
    if response.status_code == 200:
        return response
    return None


def get_xr(from_currency, from_date, to_date, response, ):
    """ Preprocessing data and getting the OBS_VALUE of x to EUR
    """
    df = pd.read_csv(io.StringIO(response.text))
    ts = df.filter(['TIME_PERIOD', 'OBS_VALUE'], axis=1)
    ts['TIME_PERIOD'] = pd.to_datetime(ts['TIME_PERIOD'])
    ts.rename({'OBS_VALUE': from_currency + " to EUR rate", }, axis=1, inplace=True)
    ts = ts.set_index('TIME_PERIOD')
    return ts


def exchange(eur_xr, from_currencies, to_currencies, from_date, to_date, suffix=" to EUR rate", ):
    """ To calculate exchange rate in from_currencies, to_currencies pairs list
    """
    from_date = from_date.strftime('%Y-%m-%d')
    to_date = to_date.strftime('%Y-%m-%d')
    result = pd.DataFrame()

    for from_currency, to_currency in zip(from_currencies, to_currencies):
        _ = pd.DataFrame()
        from_column_name = from_currency + suffix
        to_column_name = to_currency + suffix
        select_currency = eur_xr[[from_column_name, to_column_name]]
        _[from_currency + " to " + to_currency] = select_currency[from_column_name] / select_currency[to_column_name]
        result = pd.concat([result, _], axis=1)

    return result[from_date: to_date]


def create_local_dataset():
    """ making the LocalDataSet to address all concerns
        it is rate of x to EUR
    """
    currencies = ["EUR", "USD", "JPY", "BGN", "CZK", "DKK", "GBP", "HUF", "PLN", "RON", "SEK", "CHF", "ISK", "NOK",
                  "HRK", "RUB", "TRY", "AUD", "BRL", "CAD", "CNY", "HKD", "IDR", "ILS", "INR", "KRW", "MXN", "MYR",
                  "NZD", "PHP", "SGD", "THB", "ZAR"]

    last_year = (datetime.now() - relativedelta(years=1))
    today = datetime.today()

    eur_xr = pd.DataFrame()

    for from_currency in currencies:
        url = url_maker(from_currency=from_currency, )

        response = request_maker(url=url, from_date=last_year, to_date=today)

        if response is not None:
            xr = get_xr(from_currency=from_currency, from_date=last_year, to_date=today, response=response, )
            eur_xr = pd.concat([eur_xr, xr], axis=1)

    return eur_xr

In [2]:
eur_xr = create_local_dataset()
eur_xr

,USD to EUR rate,JPY to EUR rate,BGN to EUR rate,CZK to EUR rate,DKK to EUR rate,GBP to EUR rate,HUF to EUR rate,PLN to EUR rate,RON to EUR rate,SEK to EUR rate,...,ILS to EUR rate,INR to EUR rate,KRW to EUR rate,MXN to EUR rate,MYR to EUR rate,NZD to EUR rate,PHP to EUR rate,SGD to EUR rate,THB to EUR rate,ZAR to EUR rate
TIME_PERIOD,,,,,,,,,,,,,,,,,,,,,
2021-02-25,1.2225,129.73,1.9558,26.110,7.4363,0.86408,360.18,4.5122,4.8748,10.0668,...,4.0086,88.7940,1359.14,25.3424,4.9383,1.6409,59.492,1.6120,36.858,18.1101
2021-02-26,1.2121,128.83,1.9558,26.195,7.4361,0.87053,361.43,4.5186,4.8750,10.1388,...,4.0072,89.5766,1367.10,25.2879,4.9096,1.6622,59.090,1.6106,36.799,18.1025
2021-03-01,1.2053,128.63,1.9558,26.087,7.4360,0.86558,362.86,4.5263,4.8749,10.1833,...,3.9828,88.6665,1352.80,25.0317,4.8881,1.6629,58.531,1.6042,36.436,18.1498
2021-03-02,1.2028,128.58,1.9558,26.142,7.4361,0.86433,363.70,4.5322,4.8762,10.1400,...,3.9700,88.2590,1354.37,24.8772,4.8804,1.6565,58.338,1.6016,36.401,18.1353
2021-03-03,1.2048,128.81,1.9558,26.138,7.4362,0.86351,363.75,4.5336,4.8775,10.1250,...,3.9640,87.7665,1347.23,24.9919,4.8806,1.6581,58.420,1.6041,36.566,18.0073
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-02-18,1.1354,130.59,1.9558,24.337,7.4382,0.83425,356.37,4.5201,4.9453,10.5796,...,3.6276,84.6525,1356.45,23.0270,4.7528,1.6896,58.403,1.5255,36.435,17.0858
2022-02-21,1.1338,130.20,1.9558,24.345,7.4397,0.83298,357.54,4.5351,4.9448,10.6535,...,3.6433,84.6770,1353.02,22.9951,4.7387,1.6870,58.300,1.5265,36.588,17.1895
2022-02-22,1.1342,130.54,1.9558,24.496,7.4392,0.83685,355.89,4.5447,4.9464,10.5996,...,3.6584,84.7580,1353.34,23.0330,4.7472,1.6848,58.208,1.5268,36.748,17.1768
2022-02-23,1.1344,130.58,1.9558,24.473,7.4388,0.83463,357.25,4.5481,4.9468,10.5658,...,3.6515,84.6135,1350.23,22.9079,4.7480,1.6679,57.980,1.5253,36.601,17.0508
2022-02-24,1.1163,128.28,1.9558,25.090,7.4405,0.83463,368.63,4.6554,4.9501,10.7338,...,3.6618,84.2960,1347.70,22.9355,4.6896,1.6692,57.450,1.5125,36.514,17.1634

# Exchange rate could be calculate as follow:

In [3]:
last_month, today = (datetime.now() - relativedelta(months=1)), datetime.today() 

exchange(eur_xr=eur_xr, from_currencies=["USD", "JPY", "BGN"], to_currencies=["CNY", "HKD", "IDR"], from_date=last_month, to_date=today, )

             USD to CNY  JPY to HKD  BGN to IDR
TIME_PERIOD
2022-01-25     0.157981   14.646908    0.000121
2022-01-26     0.158178   14.678042    0.000121
2022-01-27     0.157048   14.806040    0.000122
2022-01-28     0.157190   14.823177    0.000122
2022-01-31     0.157209   14.804469    0.000122
2022-02-01     0.157208   14.709669    0.000121
2022-02-02     0.157207   14.660321    0.000120
2022-02-03     0.157198   14.736375    0.000120
2022-02-04     0.157207   14.752593    0.000119
2022-02-07     0.157224   14.751911    0.000119
2022-02-08     0.157057   14.808317    0.000119
2022-02-09     0.157163   14.818306    0.000119
2022-02-10     0.157298   14.854951    0.000119
2022-02-11     0.157337   14.849417    0.000120
2022-02-14     0.157304   14.793335    0.000121
2022-02-15     0.157637   14.818078    0.000121
2022-02-16     0.157723   14.830012    0.000120
2022-02-17     0.157785   14.752176    0.000120
2022-02-18     0.158046   14.744936    0.000120
2022-02-21     0.157843   14.721346    0.000120
2022-02-22     0.158030   14.751116    0.000120
2022-02-23     0.158283   14.749969    0.000120
2022-02-24     0.158114   14.714722    0.000122